
CREATE DATABASE IF NOT EXISTS PaperRecommendation DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
use PaperRecommendation; 

-- 论文基本信息表
DROP TABLE IF EXISTS PaperInfo;
CREATE TABLE PaperInfo(
    id INT NOT NULL AUTO_INCREMENT,
    author_id INT NOT NULL,
    create_time DATETIME,
    title VARCHAR(256),
    abstract TEXT,
    keywords VARCHAR(128),
    PRIMARY KEY(id)
)ENGINE=MyISAM  AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

-- 作者信息表
DROP TABLE IF EXISTS AuthorInfo;
CREATE TABLE AuthorInfo(
    id INT NOT NULL AUTO_INCREMENT,
    author_department_id INT,
    name VARCHAR(64),
    PRIMARY KEY(id)
)ENGINE=MyISAM  AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

-- 论文作者关系表
DROP TABLE IF EXISTS PaperAuthorRel;
CREATE TABLE PaperAuthorRel(
    id INT NOT NULL AUTO_INCREMENT,
    author_id INT NOT NULL,
    paper_id INT NOT NULL,
    isprimary SMALLINT NOT NULL,
    PRIMARY  KEY(ID)
)ENGINE=MyISAM  AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

-- 部门表
DROP TABLE IF EXISTS Department;
CREATE TABLE Department(
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(128),
    PRIMARY KEY(id)
)ENGINE=MyISAM  AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

-- 论文引用关系表
DROP TABLE IF EXISTS PaperRef;
CREATE TABLE PaperRef(
    id INT NOT NULL AUTO_INCREMENT,
    ref_id INT NOT NULL,
    beref_id INT NOT NULL,
    PRIMARY KEY(id)
)ENGINE=MyISAM  AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

-- 推荐结果模板表
DROP TABLE IF EXISTS RecForUser;
CREATE TABLE RecForUser(
    id INT NOT NULL AUTO_INCREMENT,
    paper_id INT NOT NULL,
    recom_time DATETIME NOT NULL,
    PRIMARY KEY(id)
)ENGINE=MyISAM  AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

